using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections;using System.Collections.Generic;using UnityEngine;using Assets.Script.DynamicCards;
public static class MotionWork{public static void Run(){new GameObject("Final actual framing check").AddComponent<MainFinalFramingCheck>();}}
public class MainFinalFramingCheck:MonoBehaviour{
const string W="C:/UnityProjects/LegacyGwent/work/DynamicCards/MotionIntegrity/";
[Serializable]class Row{public string art;public bool preview,miniature;public long pixelDelta;public float fullCorrection,thumbnailCorrection;}
[Serializable]class Report{public bool passed;public List<Row> rows=new List<Row>();}
object F(object o,string name)=>o.GetType().GetField(name,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(o);
Color32[] Pixels(DynamicCardView v){var rt=(RenderTexture)F(v,"texture");var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(rt.width,rt.height,TextureFormat.RGBA32,false);t.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);t.Apply();RenderTexture.active=old;var p=t.GetPixels32();Destroy(t);return p;}
IEnumerator Start(){yield return new WaitForSecondsRealtime(2);var views=FindObjectsOfType<DynamicCardView>().Where(v=>(string)F(v,"artId")=="12210500").ToArray();var before=views.Select(Pixels).ToArray();yield return new WaitForSecondsRealtime(3);var r=new Report();for(int i=0;i<views.Length;i++){var v=views[i];var after=Pixels(v);long delta=0;for(int n=0;n<after.Length;n++)delta+=Math.Abs(before[i][n].r-after[n].r)+Math.Abs(before[i][n].g-after[n].g)+Math.Abs(before[i][n].b-after[n].b);var entry=(DynamicCardEntry)F(v,"entry");r.rows.Add(new Row{art=entry.artIds[0],preview=(bool)F(v,"preview"),miniature=(bool)F(v,"miniature"),pixelDelta=delta,fullCorrection=entry.verticalFramingCorrection,thumbnailCorrection=entry.thumbnailFramingCorrection});}r.passed=r.rows.Count==3&&r.rows.All(a=>a.pixelDelta>0&&a.fullCorrection==.2f&&a.thumbnailCorrection==.16f)&&r.rows.Any(a=>a.preview)&&r.rows.Any(a=>a.miniature);File.WriteAllText(W+"final-framing-ui-result.json",JsonUtility.ToJson(r,true));Destroy(gameObject);}}
