using System;using System.Collections;using System.Collections.Generic;using System.Linq;using System.IO;using System.Reflection;using UnityEngine;using UnityEngine.UI;using Assets.Script.DynamicCards;using Cynthia.Card;
public class MotionWork:MonoBehaviour {
const string W="C:/UnityProjects/LegacyGwent/work/DynamicCards/MotionIntegrity/";
List<string> rows=new List<string>();List<string> errors=new List<string>();
static object F(object o,string n)=>o.GetType().GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(o);
public static void Run(){new GameObject("Local UI regression").AddComponent<MotionWork>();}
void Awake(){Application.logMessageReceived+=Log;} void OnDestroy(){Application.logMessageReceived-=Log;}
void Log(string msg,string trace,LogType t){if(t==LogType.Exception)errors.Add(msg+" "+trace);}
Color32[] Shot(DynamicCardView v,string label){var rt=(RenderTexture)F(v,"texture");if(rt==null)throw new Exception("No render texture");var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(rt.width,rt.height,TextureFormat.RGBA32,false);t.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);t.Apply();RenderTexture.active=old;var p=t.GetPixels32();if(label!=null)File.WriteAllBytes(W+"FinalUi/"+label+".png",t.EncodeToPNG());Destroy(t);return p;}
long Delta(Color32[] a,Color32[] b){long n=0;for(int i=0;i<a.Length;i++)n+=Math.Abs(a[i].r-b[i].r)+Math.Abs(a[i].g-b[i].g)+Math.Abs(a[i].b-b[i].b);return n;}
DynamicCardView[] Views()=>Resources.FindObjectsOfTypeAll<DynamicCardView>().Where(v=>v.gameObject.scene.IsValid()&&v.isActiveAndEnabled).ToArray();
bool Ready(DynamicCardView v)=>F(v,"surface")!=null&&((RawImage)F(v,"surface")).enabled&&F(v,"model")!=null;
IEnumerator WaitReady(){float start=Time.realtimeSinceStartup;while(Views().Any(v=>!Ready(v))){if(Time.realtimeSinceStartup-start>90)throw new Exception("Actual UI loading timeout");yield return null;}}
IEnumerator Start(){Directory.CreateDirectory(W+"FinalUi");var editor=Resources.FindObjectsOfTypeAll<EditorInfo>().First(x=>x.gameObject.scene.IsValid());var ids=new[]{"61001","12040","12003","70099","70179","32004"};var cards=GwentMap.GetCards(isHasAgent:true).Where(x=>ids.Contains(x.CardId)).ToList();var canvas=editor.GetComponentInParent<Canvas>();var minis=new List<ListCardShowInfo>();
foreach(var card in cards){var go=Instantiate(editor.EditorListCardPrefab,canvas.transform,false);go.name="Local tiny "+card.CardId;var rt=(RectTransform)go.transform;rt.anchorMin=rt.anchorMax=new Vector2(.5f,.5f);rt.pivot=new Vector2(.5f,.5f);rt.anchoredPosition=new Vector2(0,-100-minis.Count*65);rt.sizeDelta=new Vector2(420,60);var mini=go.GetComponent<ListCardShowInfo>();mini.SetCardInfo(card.CardId);minis.Add(mini);}
yield return WaitReady();yield return new WaitForSecondsRealtime(3);var views=Views();var before=views.Select(v=>Shot(v,"before-"+F(v,"artId")+"-"+v.GetInstanceID())).ToArray();yield return new WaitForSecondsRealtime(3);
for(int i=0;i<views.Length;i++){long delta=Delta(before[i],Shot(views[i],"after-"+F(views[i],"artId")+"-"+views[i].GetInstanceID()));rows.Add("initial art="+F(views[i],"artId")+" preview="+F(views[i],"preview")+" miniature="+F(views[i],"miniature")+" delta="+delta);if(delta==0)throw new Exception("Actual UI frozen "+F(views[i],"artId"));}
ScreenCapture.CaptureScreenshot(W+"FinalUi/screen.png");
for(int i=0;i<36;i++){editor.SetShowCardInfo(cards.Skip(i%3).ToList());editor.SelectSwitchUICard(cards[i%cards.Count]);foreach(var mini in minis)mini.SetCardInfo(cards[(i+1)%cards.Count].CardId);yield return null;}
editor.SetShowCardInfo(cards);editor.SelectSwitchUICard(cards.Last());for(int i=0;i<minis.Count;i++)minis[i].SetCardInfo(cards[i].CardId);yield return WaitReady();yield return new WaitForSecondsRealtime(2);foreach(var mini in minis){var v=mini.Miniature.GetComponent<DynamicCardView>();if((string)F(v,"artId")!=mini.CardStatus.CardArtsId)throw new Exception("Stale tiny binding");}rows.Add("36 rapid real collection/preview/tiny rebindings OK");
DynamicCardSettings.Enabled=false;yield return new WaitForSecondsRealtime(2);if(Views().Any(v=>F(v,"surface")!=null&&((RawImage)F(v,"surface")).enabled))throw new Exception("Setting off still displays dynamic surface");rows.Add("setting off static fallback OK");DynamicCardSettings.Enabled=true;yield return WaitReady();yield return new WaitForSecondsRealtime(2);views=Views();before=views.Select(v=>Shot(v,null)).ToArray();yield return new WaitForSecondsRealtime(3);for(int i=0;i<views.Length;i++){var delta=Delta(before[i],Shot(views[i],null));if(delta==0)throw new Exception("Setting resume frozen");rows.Add("setting-resume art="+F(views[i],"artId")+" delta="+delta);}foreach(var mini in minis)Destroy(mini.gameObject);yield return null;rows.Add("exceptions="+errors.Count);rows.AddRange(errors);File.WriteAllLines(W+"final-ui-result.txt",new[]{errors.Count==0?"OK":"FAIL"}.Concat(rows));Destroy(gameObject);
}
}