using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections;using UnityEngine;using UnityEditor;using Assets.Script.DynamicCards;
public static class MotionWork{public static void Run(){new GameObject("Modern Iris comparison").AddComponent<ModernIrisProbe>();}}
public class ModernIrisProbe:MonoBehaviour{
const string W="C:/UnityProjects/LegacyGwent/work/DynamicCards/MotionIntegrity/ScrollAndFramingRepair/";
object F(object o,string n)=>o.GetType().GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(o);
GameObject model;DynamicCardEffects effects;DynamicCardSourceControllers controls;float age;Camera camera;RenderTexture rt;
void LateUpdate(){if(model==null)return;age+=Time.unscaledDeltaTime;effects.Tick(age);controls.Tick(age,Time.unscaledDeltaTime,0,0);}
void Save(int frame){camera.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(1024,1024,TextureFormat.RGBA32,false);t.ReadPixels(new Rect(0,0,1024,1024),0,0);t.Apply();RenderTexture.active=old;File.WriteAllBytes(W+"iris-modern-"+frame+".png",t.EncodeToPNG());Destroy(t);}
IEnumerator Start(){var v=FindObjectsOfType<DynamicCardView>().First(x=>(string)F(x,"artId")=="20008300"&&(bool)F(x,"preview")&&F(x,"model")!=null);var original=(GameObject)F(v,"model");var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/DynamicCards/Content/Latest/13860101/Card.prefab");var data=JsonUtility.FromJson<DynamicCardEntry>(File.ReadAllText(W+"iris-modern-entry.json"));model=Instantiate(prefab);model.transform.position=new Vector3(500,500,0);model.SetActive(true);foreach(Transform child in model.transform){child.localRotation=Quaternion.identity;if(child.localPosition.sqrMagnitude>1000000)child.localPosition=Vector3.zero;}foreach(var a in model.GetComponentsInChildren<Animator>(true)){a.applyRootMotion=false;a.cullingMode=AnimatorCullingMode.AlwaysAnimate;a.Rebind();a.Update(0);}foreach(var s in model.GetComponentsInChildren<SkinnedMeshRenderer>(true)){s.quality=SkinQuality.Bone4;s.updateWhenOffscreen=true;}camera=new GameObject("Modern Iris camera").AddComponent<Camera>();camera.enabled=false;camera.transform.position=model.transform.position+new Vector3(0,0,data.cameraDistance);camera.fieldOfView=data.fieldOfView;camera.nearClipPlane=data.nearClip;camera.farClipPlane=data.farClip;camera.aspect=1;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=Color.clear;camera.allowHDR=false;rt=new RenderTexture(1024,1024,24);camera.targetTexture=rt;var p=camera.projectionMatrix;p.m12-=.240449f;camera.projectionMatrix=p;effects=model.AddComponent<DynamicCardEffects>();effects.Initialize(data);controls=model.AddComponent<DynamicCardSourceControllers>();controls.Initialize(data,camera.transform);for(int i=0;i<8;i++){yield return new WaitForSecondsRealtime(2);Save(i);}File.WriteAllText(W+"iris-modern-probe-done.txt","OK");Destroy(model);Destroy(camera.gameObject);rt.Release();Destroy(rt);Destroy(gameObject);}}
