#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections;using System.Text;using System.Reflection;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;using Assets.Script.DynamicCards;
public class AguaraProbe:MonoBehaviour {
const string W="C:/UnityProjects/LegacyGwent/work/DynamicCards/AguaraRepair-20260911/";
static object F(object o,string n)=>o.GetType().GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(o);
public static void Run(){EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);new GameObject("Aguara probe").AddComponent<AguaraProbe>();EditorApplication.isPlaying=true;}
void Awake(){Application.logMessageReceived+=(m,t,k)=>{if(k==LogType.Exception){File.WriteAllText(W+"error.txt",m+"\n"+t);EditorApplication.Exit(1);}};}
void Capture(DynamicCardView v,string name){var c=(Camera)F(v,"renderCamera");c.Render();var rt=c.targetTexture;var old=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(rt.width,rt.height,TextureFormat.RGBA32,false);tex.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);tex.Apply();RenderTexture.active=old;File.WriteAllBytes(W+name+".png",tex.EncodeToPNG());Destroy(tex);}
IEnumerator Start(){Application.runInBackground=true;Application.targetFrameRate=60;QualitySettings.vSyncCount=0;DynamicCardSettings.Enabled=true;var can=new GameObject("Canvas",typeof(Canvas)).GetComponent<Canvas>();can.renderMode=RenderMode.ScreenSpaceOverlay;var im=new GameObject("Image",typeof(RectTransform),typeof(CanvasRenderer),typeof(Image)).GetComponent<Image>();im.transform.SetParent(can.transform,false);im.rectTransform.sizeDelta=new Vector2(100,140);DynamicCardView.Bind(im,"20005600",largePreview:true,playPreviewAudio:false);var v=im.GetComponent<DynamicCardView>();float start=Time.realtimeSinceStartup;while(F(v,"surface")==null||!((RawImage)F(v,"surface")).enabled){if(Time.realtimeSinceStartup-start>90)throw new Exception("Timeout");yield return null;}
yield return new WaitForSecondsRealtime(3);Capture(v,"baseline-3s");yield return new WaitForSecondsRealtime(5);Capture(v,"baseline-8s");var model=(GameObject)F(v,"model");var sb=new StringBuilder();int index=0;foreach(var r in model.GetComponentsInChildren<ParticleSystemRenderer>(true)){var ps=r.GetComponent<ParticleSystem>();sb.AppendLine(index+" "+r.name+" enabled="+r.enabled+" count="+ps.particleCount+" mode="+r.renderMode+" mesh="+(r.mesh==null?"none":r.mesh.name)+" materials="+string.Join(";",r.sharedMaterials.Where(m=>m!=null).Select(m=>m.name+" shader="+m.shader.name+" tex="+(m.mainTexture==null?"none":m.mainTexture.name))));if(r.enabled&&r.gameObject.activeInHierarchy){r.enabled=false;Capture(v,"hide-"+index+"-"+r.name.Replace('/','_'));r.enabled=true;}index++;}File.WriteAllText(W+"particles.txt",sb.ToString());File.WriteAllText(W+"probe-done.txt","PASS");EditorApplication.Exit(0);}
}
#endif
