#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;using Assets.Script.DynamicCards;
public class RaghMotionProbe:MonoBehaviour{
const string W="C:/UnityProjects/LegacyGwent/work/DynamicCards/RaghRepair-20260911/Delivered/";
[Serializable]class Pose{public string path;public Vector3 position,scale;public Quaternion rotation;}[Serializable]class AnimatorRow{public string path,controller,clips;public bool enabled;public float speed,time;}
[Serializable]class SkinRow{public string path;public int bones,vertices;public float maxVertexDelta;}
[Serializable]class Row{public string art,mode;public string[] materialTextures;public int sample;public float age;public AnimatorRow[] animators;public Pose[] transforms;public SkinRow[] skins;}
[Serializable]class Report{public bool complete;public List<Row> rows=new List<Row>();}Report report=new Report();
Dictionary<SkinnedMeshRenderer,Vector3[]> originals=new Dictionary<SkinnedMeshRenderer,Vector3[]>();static object F(object o,string n)=>o.GetType().GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(o);
static string PathOf(Transform t,Transform root){return t==root?"":PathOf(t.parent,root)+"/"+t.name;}
public static void Run(){EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);new GameObject("Motion symptoms").AddComponent<RaghMotionProbe>();EditorApplication.isPlaying=true;}
void Awake(){Application.logMessageReceived+=Log;}void Log(string m,string trace,LogType type){if(type==LogType.Exception){File.WriteAllText(W+"baseline-error.txt",m+"\n"+trace);EditorApplication.Exit(1);}}
void Sample(DynamicCardView v,int sample){var root=((GameObject)F(v,"model")).transform;var art=(string)F(v,"artId");var mode=(bool)F(v,"preview")?"large":"small";var skins=new List<SkinRow>();foreach(var skin in root.GetComponentsInChildren<SkinnedMeshRenderer>(true)){var mesh=new Mesh();skin.BakeMesh(mesh);var vertices=mesh.vertices;float delta=0;Vector3[] first;if(!originals.TryGetValue(skin,out first))originals[skin]=vertices;else if(first.Length==vertices.Length)for(int i=0;i<vertices.Length;i++)delta=Mathf.Max(delta,Vector3.Distance(first[i],vertices[i]));skins.Add(new SkinRow{path=PathOf(skin.transform,root),bones=skin.bones.Length,vertices=vertices.Length,maxVertexDelta=delta});Destroy(mesh);}
report.rows.Add(new Row{art=art,mode=mode,sample=sample,materialTextures=root.GetComponentsInChildren<Renderer>(true).SelectMany(r=>r.sharedMaterials).Where(m=>m!=null).Select(m=>m.name+"="+(m.HasProperty("_MainTex")&&m.GetTexture("_MainTex")!=null?m.GetTexture("_MainTex").name:"none")).Distinct().ToArray(),age=(float)F(v,"age"),skins=skins.ToArray(),animators=root.GetComponentsInChildren<Animator>(true).Select(a=>new AnimatorRow{path=PathOf(a.transform,root),enabled=a.isActiveAndEnabled,controller=a.runtimeAnimatorController==null?"none":a.runtimeAnimatorController.name,speed=a.speed,time=a.runtimeAnimatorController==null?0:a.GetCurrentAnimatorStateInfo(0).normalizedTime,clips=a.runtimeAnimatorController==null?"":string.Join(",",a.GetCurrentAnimatorClipInfo(0).Select(x=>x.clip.name+" "+x.weight))}).ToArray(),transforms=root.GetComponentsInChildren<Transform>(true).Select(t=>new Pose{path=PathOf(t,root),position=t.localPosition,rotation=t.localRotation,scale=t.localScale}).ToArray()});var cam=(Camera)F(v,"renderCamera");cam.Render();var rt=cam.targetTexture;var old=RenderTexture.active;RenderTexture.active=rt;var image=new Texture2D(rt.width,rt.height,TextureFormat.RGBA32,false);image.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);image.Apply();RenderTexture.active=old;File.WriteAllBytes(W+"Baseline/"+art+"-"+mode+"-"+sample+".png",image.EncodeToPNG());Destroy(image);File.WriteAllText(W+"baseline-progress.json",JsonUtility.ToJson(report,true));}
IEnumerator Start(){Directory.CreateDirectory(W+"Baseline");Application.runInBackground=true;Application.targetFrameRate=60;QualitySettings.vSyncCount=0;DynamicCardSettings.Enabled=true;var canvas=new GameObject("Canvas",typeof(Canvas)).GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var views=new List<DynamicCardView>();foreach(string id in new[]{"11310100","20005600"})foreach(bool preview in new[]{false,true}){var im=new GameObject("Image",typeof(RectTransform),typeof(CanvasRenderer),typeof(Image)).GetComponent<Image>();im.transform.SetParent(canvas.transform,false);im.rectTransform.sizeDelta=new Vector2(100,140);im.rectTransform.anchoredPosition=new Vector2((views.Count/2-2)*125,preview?85:-85);DynamicCardView.Bind(im,id,largePreview:preview,playPreviewAudio:false);var v=im.GetComponent<DynamicCardView>();views.Add(v);float start=Time.realtimeSinceStartup;while(F(v,"surface")==null||!((RawImage)F(v,"surface")).enabled){if(Time.realtimeSinceStartup-start>90)throw new Exception("Timeout "+id);yield return null;}}
int sample=0;foreach(float wait in new[]{.1f,3f,5f,10f}){yield return new WaitForSecondsRealtime(wait);foreach(var v in views)Sample(v,sample);sample++;}foreach(var v in views)v.gameObject.SetActive(false);yield return new WaitForSecondsRealtime(.5f);foreach(var v in views)v.gameObject.SetActive(true);yield return new WaitForSecondsRealtime(2f);foreach(var v in views)Sample(v,4);report.complete=true;File.WriteAllText(W+"baseline-results.json",JsonUtility.ToJson(report,true));EditorApplication.Exit(0);}
}
#endif
